name: Add a new GitHub issue to the specified project column
on: [issues, pull_request]
jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
      - name: add-new-issues-to-organization-based-project-column
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.all_in_one_project_secret }}
          GITHUB_PROJECT_URL: https://github.com/orgs/bulderbank/projects/1
          GITHUB_PROJECT_COLUMN_NAME: '📚 Backlog'
      - name: add-new-prs-to-repository-based-project-column
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.all_in_one_project_secret }}
          GITHUB_PROJECT_URL: https://github.com/orgs/bulderbank/projects/1
          GITHUB_PROJECT_COLUMN_NAME: '⏳ In Progress'
      - name: resolved-pr-closes-linked-issues
        uses: frealmyr/gha-mjolnir@v1.0.2-f
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        with:
          GITHUB_TOKEN: ${{ secrets.all_in_one_project_secret }}
